# Generated by Django 3.1.5 on 2021-04-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
