# Generated by Django 3.1.7 on 2021-05-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guruhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
