# Generated by Django 3.1.5 on 2021-03-14 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guruhub', '0002_auto_20210313_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=50)),
                ('star', models.IntegerField()),
                ('about', models.CharField(max_length=200)),
                ('taught', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('mode', models.CharField(max_length=20)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guruhub.tutor')),
            ],
        ),
    ]
