# Generated by Django 3.1.5 on 2021-04-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guruhub', '0005_auto_20210328_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='about',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='address',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='pic',
            field=models.ImageField(default=None, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='rate',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='star',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='taught',
            field=models.IntegerField(default=None),
        ),
    ]
