# Generated by Django 3.0.4 on 2021-04-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guruhub', '0006_tutor_num'),
        ('guruhub', '0007_auto_20210428_0413'),
    ]

    operations = [
    ]
