# Generated by Django 3.1.5 on 2021-04-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guruhub', '0007_auto_20210428_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.CharField(max_length=50)),
                ('student', models.CharField(max_length=50)),
            ],
        ),
    ]
