# Generated by Django 3.1.5 on 2021-05-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guruhub', '0008_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='starcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='star',
            field=models.FloatField(blank=True),
        ),
    ]
