# Generated by Django 3.1.7 on 2021-05-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guruhub', '0009_auto_20210503_0858'),
        ('guruhub', '0008_merge_20210428_1801'),
    ]

    operations = [
    ]
