# Generated by Django 3.0.4 on 2021-05-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guruhub', '0009_auto_20210503_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
