# Generated by Django 3.1.7 on 2021-05-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guruhub', '0010_merge_20210503_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='num',
        ),
    ]
