# Generated by Django 3.0.4 on 2021-05-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guruhub', '0012_tutor_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='num',
        ),
    ]
