# Generated by Django 3.0.4 on 2021-05-06 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.CharField(max_length=50)),
                ('student', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(blank=True, upload_to='pics')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('star', models.FloatField(blank=True)),
                ('starcount', models.IntegerField(default=0)),
                ('about', models.CharField(blank=True, max_length=200)),
                ('taught', models.IntegerField(blank=True)),
                ('rate', models.IntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('mode', models.CharField(max_length=20)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guruhub.Tutor')),
            ],
        ),
    ]
